/////////////////////////////////////////////////////////////////////////
//
//	データリテラル
//
/////////////////////////////////////////////////////////////////////////
//
//
//
//
//
//
//
//
//
//

//配列リテラルヘルパー
//
// 定数要素配列= _getLiteral( 定数配列, 行番号 );
//
function _getLiteral( val_, i_ )
{
	var hc= val_[0];
	var r= [];
	
	//成形
	for( var i=0; i<hc; i++ ) r.add(val_[(i_*hc)+i+1]);
	
	return r;
}

//
// 定数要素配列= _getLiteral( 定数配列, 検索項目, 検索対象 );
//
function _getLiteralf( val_, tx_, id_=0 )
{
	var hc= val_[0];
	var max= (val_.count-1)\hc;
	
	var ri= -1;
	
	//検索
	for( var i=0; i<max; i++ ){
		var ss= val_[(i*hc)+id_+1];
		if( tx_==ss ){ ri=(i*hc)+1; break; }
	}
	
	var r= void;
	
	//成形
	if(ri>-1){
		r= [];
		for( var i=0; i<hc; i++ ) r.add(val_[ri+i]);
	}
	
	return r;
}

//定数
var _SYSTEM_VOLUME_MAX= 1.0;
var _BGM_VOLUME_MAX= 0.48;
var _SE01_VOLUME_MAX= 1.0;
var _SE02_VOLUME_MAX= 0.67;
var _BGV_VOLUME_MAX= 0.67;
var _MOVIE_VOLUME_MAX= 0.36;

			//難易度ごとの各種基本設定
			//Non eas Nor Har Ver Nidhogg
var _STANDARD_FOOD     = [900,500,350,300,250,200,250,250,250,250 ];//食料　増加量
var _STANDARD_RESOURCE = [900,500,350,300,250,200,250,250,250,250 ];//資源　増加量
var _STANDARD_ENERGY   = [900,500,350,300,250,200,250,250,250,250 ];//魔力　増加量
var _STANDARD_GOLD     = [900,500,350,300,250,200,250,250,250,250 ];//お金　増加量

			//Non eas Nor Har Ver Nidhogg
var _STANDARD_ADDHP    = [ 30, 50, 40, 30, 20, 20, 30, 30, 30, 30 ];//自軍自動ＨＰ回復値
var _STANDARD_ADDEXP   = [  0,  0,  0,  0,  0,  0,  0,  0,  0,  0 ];//自軍自動ＥＸＰ獲得値
var _STANDARD_ADDEMHP  = [400, 25, 50, 75,100,150, 50, 50, 50, 50 ];//敵軍自動ＨＰ回復値

var _ATTACKMAX= 4;	//攻撃判定値

// 
var _FRIENDSHIPADD1= 1;	//親交増加値
var _FRIENDSHIPADD2= 0.5;	//親交増加値同時選択
var _TRAININGADD1= 1;	//調教増加値
var _TRAININGADD2= 0.5;	//調教増加値同時選択

//debug
var _TESTSTATE= 5;

var _DIFF_TEXTNAME= [
					"",
					"イージー",
					"ノーマル",
					"ハード",
					"ベリーハード",
					"ニーズヘグ",
					"6",
					"7",
					"8",
					"9"
				];

var _ITEM_TYPE= [ 	3,
					 0, "片手武器",	"item_icon00",
					 1, "両手武器",	"item_icon01",
					 2, "射撃武器",	"item_icon02",
					 3, "杖",		"item_icon03",
					 4, "鞭",		"item_icon04",
					 5, "爪",		"item_icon05",
					 6, "盾",		"item_icon06",
					 7, "鎧",		"item_icon07",
					 8, "獣装",		"item_icon08",
					 9, "法衣",		"item_icon09",
					10, "道具",		"item_icon10",
					11, "素材",		"item_icon10"
	];
	
var _FRAG_TYPE= [ 	3,
					 0, "ロキ軍",			"flag01",
					 1, "エッダ軍",			"flag02",
					 2, "フォルク軍",		"flag03",
					 3, "トルドハイム軍",		"flag04",
					 4, "グラーズ軍",		"flag05",
					 5, "ヴァルハラ軍",		"flag06",
					 6, "ヨルム軍",			"flag07",
					 7, "フェンリル軍",		"flag08",
					 8, "ヘル軍",			"flag09",
					 9, "イミル軍",			"flag10",
					10, "ウトガルド軍",		"flag11",
					11, "皇族姉妹軍",		"flag12",
					12, "終末教軍",			"flag13",
					13, "新生ウトガルド軍",		"flag14",
					14, "神聖ヴァルハラ軍",		"flag15",
					98, "",		""
	];

//建設可能地形ID -1:すべて
var _ITEM_BUILD_TYPE_STATE= [ 	2,
					 0, "全て",
					 1, "平地",
					 2, "市街",
					 3, "水場",
					 4, "森",
					 5, "山岳",
					 6, "魔界"
	];
	
var _ITEM_MAP_COUNTRY= [ 	2,
					 0, "中立地帯",
					 1, "エッダ",
					 2, "トルドハイム",
					 3, "フォルク",
					 4, "グラーズ",
					 5, "ヴァルハラ",
					 6, "魔王戦艦",
					 7, "ウトガルド"

	];
	
var _ITEM_MAP_TYPE_CATEGORY= [ 	2,
					 0, "その他",
					 1, "都市",
					 2, "首都",
					 3, "隠し"

	];
	
var _CHAR_OPEN= [ 	25,		// 　 ブレイダー	　ランサー		　シューター		　キャスター		　ガーダー		　デストロイヤー
					 0,  10, 240,  90,   0,	   70,  50,  41,   0,	  20, 150,   0, 250,	  60,  80,  21,   0,	  30,   0,   0, 790,	  40,   0, 340,   0,//亜人ユニット
					 1, 120, 130, 190, 121,	  140, 100, 220, 900,	   0, 180, 200,   0,	   0,   0, 110,   0,	   0,   0, 230, 910,	 160, 272, 210, 170,//魔獣ユニット
					 2,   0,1370,1340,   0,	    0,   0,   0, 390,	1090,1380, 370,   0,	 360, 350,1330,   0,	   0, 380,1360,   0,	   0,   0,1350,   0,//妖精ユニット
					 3,1150, 280, 310,1920,	 1240,   0,   0,   0,	1140, 270, 290,1910,	1250, 260, 300,1900,	 271,   0, 330, 331,	   0,   0, 320,   0,//倭国ユニット
					 4, 400, 490,   0,   0,	  450,   0,   0, 520,	 420,   0,   0,   0,	 460, 500, 430, 440,	   0, 510, 470, 511,	   0,   0, 410, 480,//悪魔ユニット
					 5, 540,   0, 580, 610,	    0,   0,   0, 640,	 550,   0, 590,   0,	   0, 431, 600,   0,	 530,   0, 620, 630,	 560, 570, 650,   0,//不死ユニット
					 6,   0,   0,   0,   0,	    0,   0, 651, 720,	   0,   0,   0, 690,	   0, 710,   0,1091,	 670,   0, 661,   0,	   0, 660, 680, 700,//造魔ユニット
					 7, 740,   0, 781,   0,	    0,   0, 780, 785,	 750,   0, 782,   0,	   0, 760,   0, 787,	 730, 731, 783, 732,	   0, 770, 784, 786,//竜族ユニット
					 8,1010,   0,1290,   0,	 1040,1060,1510,1410,	1020,   0,1280,   0,	1080,   0,   0,1490,	1030,1070,   0,1430,	1071,1072,1300,1301,//兵卒ユニット
					 9,1100,1110,1452,1270,	 1170,1440,1460,1520,	1200,1120,1451,   0,	1160,1310,1450,   0,	   0,   0,1470,1500,	1190,1210,1161,1480,//傭兵ユニット
					10,1130,   0,1131,   0,	 1230,   0,1231,   0,	1180,1400,1181,   0,	1050,1320,1260,1321,	1220,   0,1221,1420,	   0,   0,   0,1390,//聖職ユニット
					11,1730,1780,1840,1700,	 1870,1770,1830,1702,	1710,1750,1810,1703,	1720,1800,1860,   0,	1741,1760,1820,1701,	1740,1790,1850,   0,//神族ユニット
					12,   0,   0,   0,   0,	    0,   0,   0,   0,	   0,   0,   0,   0,	   0,   0,   0,   0,	   0,   0,   0,   0,	   0,   0,   0,   0 //
	];
	
var _CHAR_OPEN_MEDALION= [ 	25,		// 　 ブレイダー	　ランサー	　シューター		　キャスター		　ガーダー		　デストロイヤー
					 0,   1,   1,   4, 999,	    1,   1,  20, 999,	   1,   1, 999,  20,	   1,   1,  22, 999,	   1, 999, 999,  26,	   1, 999,   7, 999,//亜人ユニット
					 1,   1,   1,   5,  28,	    1,   6,   9,  27,	 999,   1,   9, 999,	 999, 999,   6, 999,	 999, 999,   9,  27,	   1,   7,   6,  11,//魔獣ユニット
					 2, 999,   1,  22, 999,	  999, 999, 999,  11,	   1,   1,   5, 999,	   1,   1,  22, 999,	 999,  22,  22, 999,	 999, 999,  22, 999,//妖精ユニット
					 3,   1,  23,  24,  28,	   23, 999, 999, 999,	  19,  23,  23,  28,	  23,  23,  23,  28,	  23, 999,   7,  27,	 999, 999,  23, 999,//倭国ユニット
					 4,   1,   1, 999, 999,	    1, 999, 999,  12,	   1, 999, 999, 999,	   5,  22,   5,  11,	 999,  20,   5,  12,	 999, 999,  22,  12,//悪魔ユニット
					 5,   8, 999,  11,  11,	  999, 999, 999,  12,	   5, 999,  22, 999,	 999,   8,   5, 999,	   8, 999,  24,  11,	   1,   8,   6, 999,//不死ユニット
					 6, 999, 999, 999, 999,	  999, 999,   9,  12,	 999, 999, 999,  26,	 999,   4, 999,  26,	   1, 999,   7, 999,	 999,   7,  12,  12,//造魔ユニット
					 7,   1, 999,   4, 999,	  999, 999,   7,  10,	   1, 999,  10, 999,	 999,  10, 999,  28,	   1,   4,  10,  10,	 999,  10,  10,  12,//竜族ユニット
					 8,   1, 999,  20, 999,	    1,  20,  24,  25,	   1, 999,  20, 999,	   1, 999, 999,  22,	   1,   1, 999,  25,	   1,   1,  24,  25,//兵卒ユニット
					 9,   1,   1,  24,  24,	   19,  24,  24,  24,	   1,  19,  24, 999,	  21,   5,  24, 999,	 999, 999,  24,  25,	   1,  19,  22,  24,//傭兵ユニット
					10,   1, 999,  21, 999,	   20, 999,  21, 999,	  19,   6,  21, 999,	   1,  21,   5,  25,	  20, 999,  21,  25,	 999, 999, 999,  25,//聖職ユニット
					11,  26,  26,  27,  28,	   26,  26,  27,  28,	  26,  26,  27,  28,	  25,  27,  27, 999,	  26,  26,  27,  28,	  26,  27,  27, 999,//神族ユニット
					12, 999, 999, 999, 999,	  999, 999, 999, 999,	 999, 999, 999, 999,	 999, 999, 999, 999,	 999, 999, 999, 999,	 999, 999, 999, 999 //
	];                                                                                                                                                                               

var _CHAR_DATA_TYPE= [ 	3,
					0, "B","ch_typeB",
					1, "L","ch_typeL",
					2, "S","ch_typeS",
					3, "C","ch_typeC",
					4, "G","ch_typeG",
					5, "D","ch_typeD"
	];
	
var _CHAR_DATA_DIVINE= [ 	3,
					0, "火","moon01",
					1, "氷","moon05",
					2, "風","moon02",
					3, "土","moon06",
					4, "雷","moon07",
					5, "水","moon03",
					6, "光","moon08",
					7, "闇","moon04"
	];


var _ITEM_MEDALION= [ 	6, //index,名前,レアリティー,初期個数,価格,画像ファイル
					 0,  "魔獣のメダリオン", 0,5,  250,"btl_draft_m01",
					 1,  "悪魔のメダリオン", 0,5,  250,"btl_draft_m02",
					 2,  "異形のメダリオン", 0,5,  250,"btl_draft_m03",
					 3,  "海のメダリオン"  , 1,0,  500,"btl_draft_m04",
					 4,  "魔術のメダリオン", 1,0,  500,"btl_draft_m05",
					 5,  "毒のメダリオン"  , 1,0,  500,"btl_draft_m06",
					 6,  "巨人のメダリオン", 1,0,  750,"btl_draft_m07",
					 7,  "死者のメダリオン", 1,0,  750,"btl_draft_m08",
					 8,  "造魔のメダリオン", 2,0, 2000,"btl_draft_m09",
					 9,  "竜のメダリオン"  , 2,0, 2000,"btl_draft_m10",
					 10, "血のメダリオン"  , 2,0, 2000,"btl_draft_m11",
					 11, "魂のメダリオン"  , 3,0, 6000,"btl_draft_m12",
					 12, "王のメダリオン"  , 4,0,15000,"btl_draft_m13",
					 13, "力のメダリオン"  , 0,5,  250,"btl_draft_m14",
					 14, "技のメダリオン"  , 0,5,  250,"btl_draft_m15",
					 15, "守りのメダリオン", 0,5,  250,"btl_draft_m16",
					 16, "剣のメダリオン"  , 0,5,  250,"btl_draft_m17",
					 17, "槍のメダリオン"  , 0,5,  250,"btl_draft_m18",
					 18, "斥候のメダリオン", 1,0,  500,"btl_draft_m19",
					 19, "騎士のメダリオン", 1,0,  750,"btl_draft_m20",
					 20, "神聖のメダリオン", 1,0,  750,"btl_draft_m21",
					 21, "妖精のメダリオン", 1,0,  500,"btl_draft_m22",
					 22, "倭国のメダリオン", 1,0,  750,"btl_draft_m23",
					 23, "勇者のメダリオン", 2,0, 2000,"btl_draft_m24",
					 24, "英雄のメダリオン", 3,0, 6000,"btl_draft_m25",
					 25, "使徒のメダリオン", 4,0,15000,"btl_draft_m26",
					 26, "神のメダリオン"  , 5,0,150000,"btl_draft_m27",
					 27, "尾のメダリオン"  , 5,0,150000,"btl_draft_m28",
					 28, "",9,0,0,"btl_draft_m01",
					 29, "メダリオン素材",0,5,0,"btl_draft_m30"
	];

var _SLGBGM= [//昼基本,夜基本,　条件,ファイル名,...
				"bgm11.ogg","bgm05.ogg",

				//●１章
				"f.BGM_ID == 0 && f.used.time.turn%2  == 0 ","bgm11.ogg",
				"f.BGM_ID == 0 && f.used.time.turn%2  == 1 ","bgm05.ogg",
				"f.BGM_ID == 1 && f.used.time.turn%2  == 0 ","bgm31.ogg",
				"f.BGM_ID == 1 && f.used.time.turn%2  == 1 ","bgm05.ogg",

				//●２～５章　フォルク
				"f.BGM_ID == 10 && f.used.time.turn%2 == 0 ","bgm12.ogg",
				"f.BGM_ID == 10 && f.used.time.turn%2 == 1 ","bgm05.ogg",
				"f.BGM_ID == 11 && f.used.time.turn%2 == 0 ","bgm31.ogg",
				"f.BGM_ID == 11 && f.used.time.turn%2 == 1 ","bgm05.ogg",

				//●２～５章　トルドハイム
				"f.BGM_ID == 20 && f.used.time.turn%2 == 0 ","bgm13.ogg",
				"f.BGM_ID == 20 && f.used.time.turn%2 == 1 ","bgm05.ogg",
				"f.BGM_ID == 21 && f.used.time.turn%2 == 0 ","bgm13.ogg",
				"f.BGM_ID == 21 && f.used.time.turn%2 == 1 ","bgm17.ogg",

				//●２～５章　グラーズ
				"f.BGM_ID == 30 && f.used.time.turn%2 == 0 ","bgm14.ogg",
				"f.BGM_ID == 30 && f.used.time.turn%2 == 1 ","bgm05.ogg",
				"f.BGM_ID == 31 && f.used.time.turn%2 == 0 ","bgm14.ogg",
				"f.BGM_ID == 31 && f.used.time.turn%2 == 1 ","bgm16.ogg",

				//●２～５章　ヴァルハラ
				"f.BGM_ID == 40 && f.used.time.turn%2 == 0 ","bgm15.ogg",
				"f.BGM_ID == 40 && f.used.time.turn%2 == 1 ","bgm05.ogg",
				"f.BGM_ID == 41 && f.used.time.turn%2 == 0 ","bgm15.ogg",
				"f.BGM_ID == 41 && f.used.time.turn%2 == 1 ","bgm18.ogg",

				//●６章　イミル戦
				"f.BGM_ID == 50 && f.used.time.turn%2 == 0 ","bgm30.ogg",
				"f.BGM_ID == 50 && f.used.time.turn%2 == 1 ","bgm19.ogg",
				"f.BGM_ID == 51 && f.used.time.turn%2 == 0 ","bgm31.ogg",
				"f.BGM_ID == 51 && f.used.time.turn%2 == 1 ","bgm19.ogg",
				"f.BGM_ID == 52 && f.used.time.turn%2 == 0 ","bgm02.ogg",
				"f.BGM_ID == 52 && f.used.time.turn%2 == 1 ","bgm19.ogg",

				//●７章　シンモラinスルト戦
				"f.BGM_ID == 60 && f.used.time.turn%2 == 0 ","td10_eds.ogg",
				"f.BGM_ID == 60 && f.used.time.turn%2 == 1 ","bgm20.ogg",
				"f.BGM_ID == 61 && f.used.time.turn%2 == 0 ","td10_eds.ogg",
				"f.BGM_ID == 61 && f.used.time.turn%2 == 1 ","bgm20.ogg",

				//●ロウ８章　帝都ウトガルド戦
				"f.BGM_ID == 70 && f.used.time.turn%2 == 0 ","td10_op.ogg",
				"f.BGM_ID == 70 && f.used.time.turn%2 == 1 ","bgm20.ogg",
				"f.BGM_ID == 71 && f.used.time.turn%2 == 0 ","bgm24.ogg",
				"f.BGM_ID == 71 && f.used.time.turn%2 == 1 ","bgm20.ogg",
				"f.BGM_ID == 72 && f.used.time.turn%2 == 0 ","td10_op.ogg",
				"f.BGM_ID == 72 && f.used.time.turn%2 == 1 ","bgm34.ogg",

				//●カオス８章　新生ヴァルハラ戦
				"f.BGM_ID == 80 && f.used.time.turn%2 == 0 ","bgm35.ogg",
				"f.BGM_ID == 80 && f.used.time.turn%2 == 1 ","td10_eds.ogg",
				"f.BGM_ID == 81 && f.used.time.turn%2 == 0 ","bgm35.ogg",
				"f.BGM_ID == 81 && f.used.time.turn%2 == 1 ","td10_eds.ogg",

				//●バトルロイヤル
				"f.BGM_ID == 90 && f.used.time.turn%2 == 0 ","bgm35.ogg",
				"f.BGM_ID == 90 && f.used.time.turn%2 == 1 ","bgm34.ogg"

	];


var _ADV_CALLBACK =[//評価式,飛び先ラベル,判定ポジション
	//"f.game_mode != 1 && !ca.avg_ck('t101') && ca.avg_ck('s101') && f.used.time.turn==7","*t101",1,0,0,0,//暁のニーベルング
	//"f.game_mode != 1 && !ca.avg_ck('t102') && ca.avg_ck('zh01') && f.used.time.turn==10","*t102",0,0,1,0//エッダ攻略戦
	//"f.game_mode != 1 && !ca.avg_ck('t101') && f.used.time.turn==6","*t101",1,0,0,0,//暁のニーベルング
	//"f.game_mode != 1 && !ca.avg_ck('t102') && f.used.time.turn==20","*t102",0,0,1,0//エッダ攻略戦

	//●ゲームの初期設定
	"f.game_mode != 1 && !ca.avg_ck('init') "	,"*init",1,0,0,0,//初期設定

	//●体験版の区切り
	"f.game_mode != 1 && !ca.avg_ck('trend')  && f.used.time.turn >= 30 && f.trialmode == 1"	,"*trend",1,0,1,0,//体験版の終了箇所

	//●Ｘ系個人イベント
	//ティルカ
	"f.game_mode != 1 && !ca.avg_ck('xa01') &&                      ca.avg_ck('za02') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa01",1,0,0,0,//守護者の迷い
	"f.game_mode != 1 && !ca.avg_ck('xa02') && ca.avg_ck('xa01') && ca.avg_ck('za03') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa02",0,0,1,0,//眠れる力とは
	"f.game_mode != 1 && !ca.avg_ck('xa03') && ca.avg_ck('xa02') && ca.avg_ck('za04') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa03",0,0,1,0,//ロキの行く先
//▲連	"f.game_mode != 1 && !ca.avg_ck('xa04') && ca.avg_ck('xa03') && ca.avg_ck('za06') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa04",1,0,0,0,//依存と従属
	"f.game_mode != 1 && !ca.avg_ck('xa05') && ca.avg_ck('xa04') && ca.avg_ck('za06') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa05",1,0,0,0,//忠誠剣
	"f.game_mode != 1 && !ca.avg_ck('xa06') && ca.avg_ck('xa05') && ca.avg_ck('za08') && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] == 1"		,"*xa06",1,0,0,0,//魔霊召喚

	//フレイヤ
	"f.game_mode != 1 && !ca.avg_ck('xb01') &&                      ca.avg_ck('zb02') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1"				,"*xb01",0,0,1,0,//月の涙
	"f.game_mode != 1 && !ca.avg_ck('xb02') && ca.avg_ck('xb01') && ca.avg_ck('zb03') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1 && f.friend['Ferna']== 1"	,"*xb02",1,0,0,0,//心のざわめき
	"f.game_mode != 1 && !ca.avg_ck('xb03') && ca.avg_ck('xb02') && ca.avg_ck('zb04') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1"				,"*xb03",1,0,0,0,//将軍の責
//▲連	"f.game_mode != 1 && !ca.avg_ck('xb04') && ca.avg_ck('xb03') && ca.avg_ck('zb05') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1"				,"*xb04",1,0,0,0,//変わる月の女神
	"f.game_mode != 1 && !ca.avg_ck('xb05') && ca.avg_ck('xb04') && ca.avg_ck('zb06') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1"				,"*xb05",1,0,0,0,//変貌の豊穣神
	"f.game_mode != 1 && !ca.avg_ck('xb06') && ca.avg_ck('xb05') && ca.avg_ck('zb08') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] == 1"				,"*xb06",1,0,0,0,//堕落の良妻賢母

	//トール
	"f.game_mode != 1 && !ca.avg_ck('xc01') &&                      ca.avg_ck('zc02') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc01",1,0,0,0,//似てない同体
	"f.game_mode != 1 && !ca.avg_ck('xc02') && ca.avg_ck('xc01') && ca.avg_ck('zc03') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc02",0,0,1,0,//ユグドラシルの矛
	"f.game_mode != 1 && !ca.avg_ck('xc03') && ca.avg_ck('xc02') && ca.avg_ck('zc04') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc03",1,0,0,0,//禍つ兆し
//▲連	"f.game_mode != 1 && !ca.avg_ck('xc04') && ca.avg_ck('xc03') && ca.avg_ck('zc05') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc04",1,0,0,0,//欲望の徒
	"f.game_mode != 1 && !ca.avg_ck('xc05') && ca.avg_ck('xc04') && ca.avg_ck('zc06') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc05",1,0,0,0,//欲望の軍団
	"f.game_mode != 1 && !ca.avg_ck('xc06') && ca.avg_ck('xc05') && ca.avg_ck('zc07') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor'] == 1"		,"*xc06",1,0,0,0,//次代に見る夢

	//リグレット
	"f.game_mode != 1 && !ca.avg_ck('xd01') &&                      ca.avg_ck('zd02') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd01",1,0,0,0,//軍師リグレット
	"f.game_mode != 1 && !ca.avg_ck('xd02') && ca.avg_ck('xd01') && ca.avg_ck('zd03') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd02",1,0,0,0,//歴史を綴る者
	"f.game_mode != 1 && !ca.avg_ck('xd03') && ca.avg_ck('xd02') && ca.avg_ck('zd04') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd03",0,0,1,0,//揺らぐ冬の女神
//▲連	"f.game_mode != 1 && !ca.avg_ck('xd04') && ca.avg_ck('xd03') && ca.avg_ck('zd05') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd04",1,0,0,0,//無垢なる堕落
	"f.game_mode != 1 && !ca.avg_ck('xd05') && ca.avg_ck('xd04') && ca.avg_ck('zd06') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd05",1,0,0,0,//覇王の伝記
	"f.game_mode != 1 && !ca.avg_ck('xd06') && ca.avg_ck('xd05') && ca.avg_ck('zd07') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret'] == 1"		,"*xd06",1,0,0,0,//すれちがい

	//オーディン
	"f.game_mode != 1 && !ca.avg_ck('xe01') &&                      ca.avg_ck('ze02') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe01",0,0,1,0,//私室の絶対神
	"f.game_mode != 1 && !ca.avg_ck('xe02') && ca.avg_ck('xe01') && ca.avg_ck('ze03') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe02",1,0,0,0,//空を見下ろす
	"f.game_mode != 1 && !ca.avg_ck('xe03') && ca.avg_ck('xe02') && ca.avg_ck('ze04') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe03",1,0,0,0,//堕落への秒読み
//▲連	"f.game_mode != 1 && !ca.avg_ck('xe04') && ca.avg_ck('xe03') && ca.avg_ck('ze05') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe04",1,0,0,0,//忠誠の絶対神
	"f.game_mode != 1 && !ca.avg_ck('xe05') && ca.avg_ck('xe04') && ca.avg_ck('ze06') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe05",1,0,0,0,//正妻ＶＳ愛人
	"f.game_mode != 1 && !ca.avg_ck('xe06') && ca.avg_ck('xe05') && ca.avg_ck('ze07') && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin'] == 1"		,"*xe06",1,0,0,0,//人気者神様

	//ヴェズルング
	"f.game_mode != 1 && !ca.avg_ck('xf01') && f.鍵喪失 != 1 && f.変異値 >= 7 "	,"*xf01",1,0,1,0,//宿命の鍵

	//フェーナ
	"f.game_mode != 1 && !ca.avg_ck('xh01') &&                                             ca.avg_ck('s201') && f.used.stat.story == 2 &&                           f.friend['Ferna']== 1"				,"*xh01",0,0,1,0,//ヴェズルング
	"f.game_mode != 1 && !ca.avg_ck('xh02') && f.ターン履歴s102 !== void && f.used.time.turn - f.ターン履歴s102 >= 6 && ca.avg_ck('s102') && f.used.stat.story == 2 &&                           f.friend['Ferna']== 1 && f.friend['Tilca'] == 1"	,"*xh02",1,0,0,0,//三角関係？
	"f.game_mode != 1 && !ca.avg_ck('xh03') && f.ターン履歴s204 !== void && f.used.time.turn - f.ターン履歴s204 >= 6 && ca.avg_ck('s204') && f.used.stat.story >= 3 && f.used.stat.story <= 6 && f.friend['Ferna']== 1 && f.friend['Thor']  == 1"	,"*xh03",1,0,0,0,//監視任務の顛末
	"f.game_mode != 1 && !ca.avg_ck('xh04') && f.ターン履歴s404 !== void && f.used.time.turn - f.ターン履歴s404 >= 6 && ca.avg_ck('s404') && f.used.stat.story >= 3 && f.used.stat.story <= 6 && f.friend['Ferna']== 1 && f.friend['Freya'] == 1"	,"*xh04",1,0,0,0,//フェーナは見た
	"f.game_mode != 1 && !ca.avg_ck('xh05') && f.ターン履歴s304 !== void && f.used.time.turn - f.ターン履歴s304 >= 6 && ca.avg_ck('s304') && f.used.stat.story >= 3 && f.used.stat.story <= 6 && f.friend['Ferna']== 1 && f.friend['Regret']== 1"	,"*xh05",1,0,0,0,//無精者
	"f.game_mode != 1 && !ca.avg_ck('xh06') && f.ターン履歴s504 !== void && f.used.time.turn - f.ターン履歴s504 >= 6 && ca.avg_ck('s504') && f.used.stat.story >= 3 && f.used.stat.story <= 6 && f.friend['Ferna']== 1 && f.friend['Odin']  == 1"	,"*xh06",1,0,0,0,//プロの揉み師


	//●個人イベント

	//ヘル

	//フェンリル

	//ヨルム


	//●Ｚ系個人イベント
	//ティルカ
//▲連	"f.game_mode != 1 && !ca.avg_ck('za11') && ca.avg_ck('za10') && f.sel_ya09 == '狂'      && f.route == 'chaos'           && f.used.stat.story == 8 && f.friend['Tilca']== 1 "	,"*za11",1,0,0,0,//狂える母性▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('za12') && f.subend == 'za12' "											,"*za12",1,0,0,0,//後宮の后★悪ティルカ：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('za13') && f.subend == 'za13' "											,"*za13",1,0,0,0,//因縁と絆の果てに★善ティルカ：サブエンド

	//フレイヤ
//▲連	"f.game_mode != 1 && !ca.avg_ck('zb09') && ca.avg_ck('zb08') && f.sel_yb09 == '狂'      && f.route == 'chaos'           && f.used.stat.story == 8 && f.friend['Freya']== 1 "	,"*zb09",1,0,0,0,//蛇神蹂躙▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zb10') && f.subend == 'zb10' "											,"*zb10",1,0,0,0,//艶美舞踏★悪フレイヤ：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('zb11') && f.subend == 'zb11' "											,"*zb11",1,0,0,0,//目指すべき未来★善フレイヤ：サブエンド

	//トール
//▲連	"f.game_mode != 1 && !ca.avg_ck('zc10') && ca.avg_ck('zc09') && f.sel_yc09 == '狂'    && f.route == 'chaos'           && f.used.stat.story == 8 && f.friend['Thor']== 1 "	,"*zc10",1,0,0,0,//戦場の凶神▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zc11') && f.subend == 'zc11' "										,"*zc11",1,0,0,0,//閨房の親衛隊★悪トール：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('zc12') && f.subend == 'zc12' "										,"*zc12",1,0,0,0,//戦士の妻★悪トール：サブエンド

	//リグレット
//▲連	"f.game_mode != 1 && !ca.avg_ck('zd09') && ca.avg_ck('zd08') && f.sel_yd09 == '狂'        && f.route == 'chaos'           && f.used.stat.story == 8 && f.friend['Regret']== 1 "	,"*zd09",1,0,0,0,//人形として▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zd10') && f.subend == 'zd10' "											,"*zd10",1,0,0,0,//揺り篭のリグレット★悪リグレット：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('zd11') && f.subend == 'zd11' "											,"*zd11",1,0,0,0,//女神の休暇★善リグレット：サブエンド

	//オーディン
//▲連	"f.game_mode != 1 && !ca.avg_ck('ze08') && f.subend == 'za08' "											,"*ze08",1,0,0,0,//暴走の悪神★悪オーディンリグレット：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('ze09') && f.subend == 'za09' "											,"*ze09",1,0,0,0,//神の末路★真オーディン：サブエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('ze10') && f.subend == 'za10' "											,"*ze10",1,0,0,0,//覇王と小さき主神★善オーディン：サブエンド

	//フェーナ

	//ヘル
//▲連	"f.game_mode != 1 && !ca.avg_ck('zk02') && ca.avg_ck('xk03') && f.used.stat.story >= 1 && f.used.stat.story <= 7 && f.friend['Hel']== 1 "	,"*zk02",1,0,0,0,//ヘルクライム▲Ｈシーン

	//フェンリル

	//ヨルム
//▲連	"f.game_mode != 1 && !ca.avg_ck('zm02') && ca.avg_ck('xm03') && f.used.stat.story >= 2 && f.used.stat.story <= 5 && f.friend['Jormu']== 1 "	,"*zm02",1,0,0,0,//ヨルムの敏感なカラダ▲Ｈシーン

	//●ダブルエッチ系
//▲連	"f.game_mode != 1 && !ca.avg_ck('zw07') && f.subend == 'zw07' "		,"*zw07",1,0,1,0,	//奈落の絶対神★姉妹神全員狂堕ち＆真オーディン凌辱エンド▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zw08') && f.subend == 'zw08' "		,"*zw08",1,0,1,0,	//３匹の番犬★悪魔三姉妹：サブエンド▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zw09') && f.subend == 'zw09' "		,"*zw09",1,0,1,0,	//二人の姉妹★フェーナ＆メニア：サブエンド▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('zw10') && f.subend == 'zw10' "		,"*zw10",1,0,1,0, 	//覇王饗宴★ハーレム：サブエンド▲Ｈシーン


	//●プロローグ
	"f.game_mode != 1 && !ca.avg_ck('s001') && ca.avg_ck('init') "						,"*s001",1,0,1,0,//序章
//▲連	"f.game_mode != 1 && !ca.avg_ck('zh01') && ca.avg_ck('s001')  "						,"*zh01",1,0,1,0,//与えられた力▲Ｈシーン
	//●１章
//▲連	"f.game_mode != 1 && !ca.avg_ck('s101') && ca.avg_ck('zh01')"						,"*s101",1,0,0,0,//ユグドラシルの女神達
	"f.game_mode != 1 && !ca.avg_ck('t101') && ca.avg_ck('s101') && f.get_enemy_status_power[1].power <=11 "	,"*t101",1,0,1,0,//暁のニーベルング（戦闘に勝利した時の発動シナリオは_DAY_PREじゃないとだめそう）
	"f.game_mode != 1 && !ca.avg_ck('t102') && ca.avg_ck('t101') && f.get_enemy_status_power[1].power <= 2 "	,"*t102",1,0,1,0,//エッダ攻略戦
//▲連	"f.game_mode != 1 && !ca.avg_ck('za01') && ca.avg_ck('t102') "						,"*za01",1,0,1,0,//聖処女堕悦▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('s102') && ca.avg_ck('za01') "						,"*s102",1,0,1,0,//動乱のユグドラシル


	//●２章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s201') && ca.avg_ck('s102') && f.used.stat.story == 2 "			,"*s201",1,0,1,0,//覇者への一里塚
	"f.game_mode != 1 && !ca.avg_ck('s200') && ca.avg_ck('s201') && f.used.time.turn - f.章頭ターン履歴 >= 2"	,"*s200",1,0,1,0,//ブラックボックス

	//●３章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s301') && f.used.stat.story == 3 "										,"*s301",1,0,1,0,//加速する戦乱
	"f.game_mode != 1 && !ca.avg_ck('s300') && ca.avg_ck('s301') && f.friend['Regret'] == 1 && f.used.time.turn - f.章頭ターン履歴 >= 2"	,"*s300",1,0,1,0,//解析ツール

	//●４章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s401') && f.used.stat.story == 4 "										,"*s401",1,0,1,0,//深まる謎
	"f.game_mode != 1 && !ca.avg_ck('s400') && ca.avg_ck('s300') && ca.avg_ck('s401') && f.used.time.turn - f.章頭ターン履歴 >= 2"		,"*s400",1,0,1,0,//歴史的発見？

	//●５章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s501') && f.used.stat.story == 5 "						,"*s500",1,0,0,0,//遠望の過去

	//●２～５章
	//●トルドハイムを選択
//▲連	"f.game_mode != 1 && !ca.avg_ck('t201') && f.used.stat.story >= 2 && f.invasion == 3 "						,"*t201",1,0,1,0,//密林戦線
	"f.game_mode != 1 && !ca.avg_ck('s202') && ca.avg_ck('t201') && f.get_enemy_status_power[3].power <= 9 && f.フェンリル同盟 == 1"	,"*s202",1,0,1,0,//淫魔の裏切り
	"f.game_mode != 1 && !ca.avg_ck('s203') &&                      f.get_enemy_status_power[7].power <= 0 "				,"*s203",1,0,1,0,//愛欲のフェンリル
//▲連	"f.game_mode != 1 && !ca.avg_ck('zl01") && ca.avg_ck('s203') && f.犯す == 1 "							,"*zl01",1,0,1,0,//淫狼触手責め▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('t202') && ca.avg_ck('s203') && f.get_enemy_status_power[3].power <= 2 "				,"*t202",1,0,1,0,//決戦トール
//▲連	"f.game_mode != 1 && !ca.avg_ck('zc01') && ca.avg_ck('t202') "									,"*zc01",1,0,1,0,//牝の洗礼▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('s204') && ca.avg_ck('zc01') "									,"*s204",1,0,1,0,//傀儡政権

	//●グラーズを選択
//▲連	"f.game_mode != 1 && !ca.avg_ck('t301') && f.used.stat.story >= 2 && f.invasion == 4 "			,"*t301",1,0,1,0,//静寂を破る進撃
	"f.game_mode != 1 && !ca.avg_ck('s302') && ca.avg_ck('t301') && f.get_enemy_status_power[4].power <= 11 "	,"*s302",1,0,1,0,//逆襲のヨルム
	"f.game_mode != 1 && !ca.avg_ck('s303') && ca.avg_ck('s302') && f.get_enemy_status_power[6].power <= 0 && f.ヨルム出現 != f.used.time.turn "	,"*s303",1,0,1,0,//プラントを制圧せよ
	"f.game_mode != 1 && !ca.avg_ck('t302') && ca.avg_ck('s303') && f.get_enemy_status_power[4].power <= 2  "	,"*t302",1,0,1,0,//勇気と怯懦
//▲連	"f.game_mode != 1 && !ca.avg_ck('zd01') && ca.avg_ck('t302') "						,"*zd01",1,0,1,0,//妖花の宿主▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('s304') && ca.avg_ck('zd01') "						,"*s304",1,0,1,0,//姉妹は共に

	//●フォルクを選択
//▲連	"f.game_mode != 1 && !ca.avg_ck('t401') && f.used.stat.story >= 2 && f.invasion == 2 "			,"*t401",1,0,1,0,//黄金の平原
	"f.game_mode != 1 && !ca.avg_ck('s402') && ca.avg_ck('t401') && f.get_enemy_status_power[2].power <= 9 "	,"*s402",0,0,1,0,//秋月の謎
	"f.game_mode != 1 && !ca.avg_ck('s403') && ca.avg_ck('s402') && f.get_enemy_status_power[2].power <= 6 "	,"*s403",1,0,1,0,//不可視の一撃
	"f.game_mode != 1 && !ca.avg_ck('t402') && ca.avg_ck('s403') && f.get_enemy_status_power[2].power <= 2 "	,"*t402",1,0,1,0,//月を射る狼
//▲連	"f.game_mode != 1 && !ca.avg_ck('zb01') && ca.avg_ck('t402') "						,"*zb01",1,0,1,0,//フレイヤ初陵辱▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('s404') && ca.avg_ck('zb01') "						,"*s404",1,0,1,0,//秋の国の完全支配

	//●ヴァルハラを選択
//▲連	"f.game_mode != 1 && !ca.avg_ck('t501') && f.used.stat.story >= 2 && f.invasion == 5 "					,"*t501",1,0,1,0,//神域への潜入
	"f.game_mode != 1 && !ca.avg_ck('s502') && ca.avg_ck('t501') && f.get_enemy_status_power[5].power <= 7 && f.ヘル同盟 == 1 "	,"*s502",1,0,1,0,//嵐の皇女
	"f.game_mode != 1 && !ca.avg_ck('s503') &&                      f.get_enemy_status_power[8].power <= 0 "			,"*s503",1,0,1,0,//皇女、迎撃戦
	"f.game_mode != 1 && !ca.avg_ck('t502') && ca.avg_ck('s503') && f.get_enemy_status_power[5].power <= 2 "			,"*t502",1,0,1,0,//絶対神の誇り
//▲連	"f.game_mode != 1 && !ca.avg_ck('ze01') && ca.avg_ck('t502') "								,"*ze01",1,0,1,0,//オーディン初陵辱▲Ｈシーン
//▲連	"f.game_mode != 1 && !ca.avg_ck('s504') && ca.avg_ck('ze01') "								,"*s504",1,0,1,0,//絶対神と共に

	//●６章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s601') && f.used.stat.story == 6 "											,"*s601",1,0,1,0,//長兄動く
	"f.game_mode != 1 && !ca.avg_ck('s600') && ca.avg_ck('s601') && !ca.avg_ck('s603') && f.治世 >= f.覇道 && f.used.time.turn - f.章頭ターン履歴 >= 2"	,"*s600",0,0,1,0,//集いし五柱
	"f.game_mode != 1 && !ca.avg_ck('s602') && ca.avg_ck('s601') && f.used.time.turn - f.章頭ターン履歴 >= 2 "						,"*s602",1,0,1,0,//終末教
	"f.game_mode != 1 && !ca.avg_ck('s603') && ca.avg_ck('s602') && f.get_enemy_status_power[9].power<= 0 &&  f.get_enemy_status_power[12].power <= 0"	,"*s603",1,0,1,0,//鍵を手にする者
	"f.game_mode != 1 && !ca.avg_ck('s604') && ca.avg_ck('s603') && f.used.mapf.territory.find(86) >= 0 "								,"*s604",1,0,1,0,//試される意志

	//●７章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s701') && f.used.stat.story == 7 "						,"*s701" ,1,0,1,0,//奪還作戦
	"f.game_mode != 1 && !ca.avg_ck('s702a')&& ca.avg_ck('s701') && gf.map[26].frag == 0 "			,"*s702a",1,0,1,0,//ティルカ救出
	"f.game_mode != 1 && !ca.avg_ck('s702b')&& ca.avg_ck('s701') && gf.map[9].frag  == 0 "			,"*s702b",1,0,1,0,//フレイヤ救出
	"f.game_mode != 1 && !ca.avg_ck('s702c')&& ca.avg_ck('s701') && gf.map[55].frag == 0 "			,"*s702c",1,0,1,0,//オーディン救出
//▲連　どう判定書いても発動に半ターン遅れが生じるのでボツ	"f.game_mode != 1 && !ca.avg_ck('s703') && ca.avg_ck('s702a')&& ca.avg_ck('s702b')&& ca.avg_ck('s702c') "	,"*s703" ,1,0,1,0,//作戦会議
	"f.game_mode != 1 && !ca.avg_ck('s704') && ca.avg_ck('s703') &&  f.get_enemy_status_power[10].power <= 0 "	,"*s704" ,1,0,1,0,//劇場攻略戦

//▲連	"f.game_mode != 1 && !ca.avg_ck('s705e')&& ca.avg_ck('s704') && f.route === 'normal' && f.gameclear == 1 "	,"*s705_end",1,0,1,0,//円環史★ノーマルエンド
//▲連	"f.game_mode != 1 && !ca.avg_ck('s706') && ca.avg_ck('s704') && f.route == 'law' "				,"*s706",1,0,1,0,//大破局（ロウルート確定）
//▲連	"f.game_mode != 1 && !ca.avg_ck('s707') && ca.avg_ck('s704') && f.route == 'chaos' "				,"*s707",1,0,1,0,//魔王と絶対神（カオスルート確定）

	//●ロウ８章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s801') && f.used.stat.story == 8 && f.route == 'law' "				,"*s801",1,0,0,0,//帝都侵攻
	"f.game_mode != 1 && !ca.avg_ck('s802') && ca.avg_ck('s801') && f.get_enemy_status_power[13].power <= 12 "	,"*s802",1,0,1,0,//英霊と虚の巨人
	"f.game_mode != 1 && !ca.avg_ck('s803') && ca.avg_ck('s802') && f.get_enemy_status_power[13].power <= 5 "	,"*s803",1,0,1,0,//手向けの焔
//▲連　どう判定書いても発動に半ターン遅れが生じるのでボツ	"f.game_mode != 1 && !ca.avg_ck('s804') && ca.avg_ck('s803') && f.used.mapf.territory.find(128) >= 0 "	,"*s804",1,0,1,0,//その前夜
	"f.game_mode != 1 && !ca.avg_ck('s805') && ca.avg_ck('s804') && f.get_enemy_status_power[13].power <= 0 "	,"*s805",1,0,1,0,//神話の日
//▲ボツ	"f.game_mode != 1 && !ca.avg_ck('s805') && ca.avg_ck('s804') && f.used.mapf.territory.find(129) >= 0 "	,"*s805",1,0,1,0,//神話の日

	"f.game_mode != 1 && !ca.avg_ck('s806e')&& ca.avg_ck('s805') && f.治世 >= f.覇道 && f.gameclear == 1"	,"*s806_end",1,0,1,0,//ヴィーナスフォール★ロウルートメイン治世エンド
	"f.game_mode != 1 && !ca.avg_ck('s807e')&& ca.avg_ck('s805') && f.治世 <  f.覇道 && f.gameclear == 1"	,"*s807_end",1,0,1,0,//覇王ロキ★ロウルートメイン覇道エンド
	"f.game_mode != 1 && !ca.avg_ck('s808e')&& ca.avg_ck('s805') && f.フェーナ好感度 >= 9 && f.gameclear == 1"	,"*s808_end",1,0,1,0,//新たなる歴史のはじまり★ロウフェーナエンド

	//●カオス８章開幕
//▲連	"f.game_mode != 1 && !ca.avg_ck('s851') && f.used.stat.story == 8 && f.route == 'chaos' "					,"*s851" ,1,0,0,0,//覇なる頂へ
	"f.game_mode != 1 && !ca.avg_ck('s852a')&& ca.avg_ck('s851') && gf.map[67].frag == 0 "				,"*s852a",1,0,1,0,//散華の一撃
	"f.game_mode != 1 && !ca.avg_ck('s852b')&& ca.avg_ck('s851') && gf.map[69].frag == 0 "				,"*s852b",1,0,1,0,//陵辱月蝕
	"f.game_mode != 1 && !ca.avg_ck('s852c')&& ca.avg_ck('s851') && gf.map[68].frag == 0 "				,"*s852c",1,0,1,0,//雷神屈服
	"f.game_mode != 1 && !ca.avg_ck('s852d')&& ca.avg_ck('s851') && gf.map[70].frag == 0 "				,"*s852d",1,0,1,0,//漆黒少女
//▲連	"f.game_mode != 1 && !ca.avg_ck('s853') && ca.avg_ck('s852a')&& f.s852b== 1 && f.s852c== 1 && f.s852d== 1"		,"*s853" ,1,0,1,0,//悪を滅する神の威光
	"f.game_mode != 1 && !ca.avg_ck('s854') && ca.avg_ck('s851') && f.get_enemy_status_power[14].power <= 0 "		,"*s854" ,1,0,1,0,//覇道の頂
	"f.game_mode != 1 && !ca.avg_ck('s854') && ca.avg_ck('s851') && f.get_enemy_status_power[14].power <= 2 && f.used.mapf.territory.find(85) >= 0 "		,"*s854" ,1,0,1,0,//覇道の頂（ヴァラスキャルヴをとって、かつ国力２以下）
//▲連	"f.game_mode != 1 && !ca.avg_ck('s855e')&& ca.avg_ck('s854') && f.gameclear == 1 "					,"*s855_end",1,0,1,0,//戦渦は嵐のように★カオスルートメインエンド

	//●ロウルート８章ウトガルド編ゲームオーバー系
	"f.game_mode != 1 && !ca.avg_ck('bade') && f.used.mapf.territory.count <= 91 && f.used.stat.story == 8 && f.route == 'law' "	,"*badend",1,0,1,0, 	//領地０のバッドエンド：サブエンド

	//●通常ゲームオーバー系
	"!ca.avg_ck('bade') && f.used.time.turn >= 999 "		,"*badend",1,0,1,0, 	//ターン数９９９のバッドエンド：サブエンド
	"!ca.avg_ck('bade') && f.used.mapf.territory.count <= 0 "	,"*badend",1,0,1,0, 	//領地０のバッドエンド：サブエンド

//-------------------------------------------------------------------------------------------------------------------------
	//●バトルロイヤル系

	"f.game_mode == 1 && !ca.avg_ck('br01') && f.get_enemy_status_power[1].power <= 2 "			,"*br01",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br02') && f.get_enemy_status_power[2].power <= 2 "			,"*br02",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br03') && f.get_enemy_status_power[3].power <= 2 "			,"*br03",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br04') && f.get_enemy_status_power[4].power <= 2 "			,"*br04",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br05') && f.get_enemy_status_power[5].power <= 2 "			,"*br05",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br06') && f.get_enemy_status_power[6].power <= 2 && f.BR_ver >= 1 "	,"*br06",1,0,1,0, 	//ヨルム（バトルロイヤルver0では発生しない）
	"f.game_mode == 1 && !ca.avg_ck('br07') && f.get_enemy_status_power[7].power <= 2 "			,"*br07",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br08') && f.get_enemy_status_power[8].power <= 2 "			,"*br08",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br09') && f.get_enemy_status_power[9].power <= 2 "			,"*br09",1,0,1,0, 	//
	"f.game_mode == 1 && !ca.avg_ck('br10') && f.get_enemy_status_power[10].power <= 0 "			,"*br10",1,0,1,0, 	//ウトガルド

	"f.game_mode == 1 && !ca.avg_ck('btlr') && f.打倒国数 >= 9 && f.BR_ver >= 1 "	,"*btlr",1,0,1,0, 	//バトルロイヤルクリアver1以降
	"f.game_mode == 1 && !ca.avg_ck('btlr') && f.打倒国数 >= 8 && f.BR_ver == 0 "	,"*btlr",1,0,1,0 	//バトルロイヤルクリアver0
//-------------------------------------------------------------------------------------------------------------------------

	];
	
	
var _CALL_CALLBACK =[//評価式,飛び先ラベル,判定ポジション

	//f.Kは　いま暫定的に　1という値が入っています。
	//●個人イベント
	//ティルカ
	"f.game_mode != 1 && !ca.avg_ck('ya01') &&			     f.used.親交値.Tilca >= 10*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 5 && f.friend['Tilca']== 1 && f.metamor01== 0 "	,"*ya01",1,0,1,0,"フェーナの挑発",0,//フェーナの挑発
	"f.used.stat.story >= 6 "	,"",1,0,1,0,"",1,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('ya02') && ca.avg_ck('ya01')  && f.used.親交値.Tilca >= 20*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 0 "	,"*ya02",1,0,1,0,"風紀の乱れは",0,//風紀の乱れは
	"f.game_mode != 1 && !ca.avg_ck('ya03') && ca.avg_ck('ya02')  && f.used.親交値.Tilca >= 30*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 0 "	,"*ya03",1,0,1,0,"商売の神",0,//商売の神
	"f.game_mode != 1 && !ca.avg_ck('ya04') && ca.avg_ck('ya03')  && f.used.親交値.Tilca >= 40*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 0 "	,"*ya04",1,0,1,0,"橋を架けた英霊",0,//橋を架けた英霊
	"f.game_mode != 1 && !ca.avg_ck('ya05') &&                       f.used.親交値.Tilca >= 50*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 1 "	,"*ya05",1,0,1,0,"娼館街構想",0,//娼館街構想
	"f.game_mode != 1 && !ca.avg_ck('ya06') && ca.avg_ck('ya05')  && f.used.親交値.Tilca >= 60*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 1 "	,"*ya06",1,0,1,0,"屈折した関係",0,//屈折した関係
	"f.game_mode != 1 && !ca.avg_ck('ya07') && ca.avg_ck('ya06')  && f.used.親交値.Tilca >= 70*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 1 "	,"*ya07",1,0,1,0,"部屋の掃除権",0,//部屋の掃除権
	"f.game_mode != 1 && !ca.avg_ck('ya08') && ca.avg_ck('ya07')  && f.used.親交値.Tilca >= 80*f.K    && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Tilca']== 1 && f.metamor01== 1 "	,"*ya08",1,0,1,0,"決闘賭博",0,//決闘賭博
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",0,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('ya09') && ca.avg_ck('s852a') && ca.avg_ck('za10')                                          && f.used.stat.story == 8 && f.friend['Tilca']== 1 && f.route == 'chaos'    "	,"*ya09",1,0,0,0,"禁断のプラント",0,//禁断のプラント
	"f.game_mode != 1 && !ca.avg_ck('ya10') && ca.avg_ck('za11')                                                                && f.used.stat.story == 8 && f.friend['Tilca']== 1 && f.route == 'chaos'    "	,"*ya10",1,0,0,0,"淫虫の母",0,//淫虫の母
	//ティルカＨ系
	"f.game_mode != 1 && !ca.avg_ck('za02') && ca.avg_ck('za01') && f.used.調教値.Tilca >= 10*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za02",1,0,1,0,"懲罰イマラチオ",0,//懲罰イマラチオ▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za03') && ca.avg_ck('za02') && f.used.調教値.Tilca >= 20*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za03",1,0,1,0,"スライム相姦",0,//スライム相姦▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za04') && ca.avg_ck('za03') && f.used.調教値.Tilca >= 30*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za04",1,0,1,0,"女神の精液漬け",0,//女神の精液漬け▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za05') && ca.avg_ck('za04') && f.used.調教値.Tilca >= 40*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za05",1,0,1,0,"堕落の兆し、欲望の発芽",0,//堕落の兆し、欲望の発芽▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za07') && ca.avg_ck('za05') && f.used.調教値.Tilca >= 50*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za07",1,0,1,0,"つがいの牝馬",0,//つがいの牝馬▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za06') && ca.avg_ck('za07') && f.used.調教値.Tilca >= 60*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za06",1,0,1,0,"堕落の生贄",0,//堕落の生贄▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw02') && ca.avg_ck('xd04') &&!ca.avg_ck('za06')             && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Tilca'] && f.friend['Regret']== 1 "	,"*zw02",1,0,1,0,"双頭姉妹責め",0,//双頭姉妹責め▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za08') && ca.avg_ck('za06') && f.used.調教値.Tilca >= 70*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za08",1,0,1,0,"絶頂フェラチオ",0,//絶頂フェラチオ▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za09') && ca.avg_ck('za08') && f.used.調教値.Tilca >= 80*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za09",1,0,1,0,"獣のまぐわい",0,//獣のまぐわい▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('za10') && ca.avg_ck('za09') && f.used.調教値.Tilca >= 90*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 "	,"*za10",1,0,1,0,"望む変貌",0,//望む変貌▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw03') && ca.avg_ck('xa04') && ca.avg_ck('xd04')             && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca'] && f.friend['Regret']== 1 "	,"*zw03",1,0,1,0,"痴女姉妹の散歩",0,//痴女姉妹の散歩▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xa07') &&!ca.avg_ck('xa04') && f.used.親交値.Tilca >= 99*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Tilca']== 1 && f.ティルカ好感度 >= 3 "	,"*xa07",1,0,1,0,"この身は剣",0,//この身は剣
	"f.friend['Tilca']== 0 || ca.avg_ck('xa07') "	,"",1,0,1,0,"",0,//ティルカイベントの解除条件（善ラストイベントをみるともうコールは発動不可）

	//フレイヤ
	"f.game_mode != 1 && !ca.avg_ck('yb01') &&                      f.used.親交値.Freya >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 0 "	,"*yb01",1,0,1,0,"平原酒場",1,//平原酒場
	"f.game_mode != 1 && !ca.avg_ck('yb02') && ca.avg_ck('yb01') && f.used.親交値.Freya >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 0 "	,"*yb02",1,0,1,0,"見通す力",1,//見通す力
	"f.game_mode != 1 && !ca.avg_ck('yb03') && ca.avg_ck('yb02') && f.used.親交値.Freya >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 0 "	,"*yb03",1,0,1,0,"天馬と月光",1,//天馬と月光
	"f.game_mode != 1 && !ca.avg_ck('yb04') && ca.avg_ck('yb03') && f.used.親交値.Freya >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 0 "	,"*yb04",1,0,1,0,"迷う女神",1,//迷う女神
	"f.game_mode != 1 && !ca.avg_ck('yb05') &&                      f.used.親交値.Freya >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 1 "	,"*yb05",1,0,1,0,"慈悲無き大軍",1,//慈悲無き大軍
	"f.game_mode != 1 && !ca.avg_ck('yb06') && ca.avg_ck('yb05') && f.used.親交値.Freya >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 1 "	,"*yb06",1,0,1,0,"娼婦の酒場",1,//娼婦の酒場
	"f.game_mode != 1 && !ca.avg_ck('yb07') && ca.avg_ck('yb06') && f.used.親交値.Freya >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 1 "	,"*yb07",1,0,1,0,"正妻と従者",1,//正妻と従者
	"f.game_mode != 1 && !ca.avg_ck('yb08') && ca.avg_ck('yb07') && f.used.親交値.Freya >= 80*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Freya']== 1 && f.metamor02 == 1 "	,"*yb08",1,0,1,0,"良妻淫婦",1,//良妻淫婦
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",1,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('yb09') && ca.avg_ck('s852b')&& ca.avg_ck('zb08')             && f.used.stat.story == 8                           && f.friend['Freya']== 1 && f.route == 'chaos'     "	,"*yb09",1,0,0,0,"堕落への急転直下",1,//堕落への急転直下
	"f.game_mode != 1 && !ca.avg_ck('yb10') && ca.avg_ck('zb09')                                  && f.used.stat.story == 8                           && f.friend['Freya']== 1 && f.route == 'chaos'     "	,"*yb10",1,0,0,0,"月に吠える蛇神",1,//月に吠える蛇神
	//フレイヤＨ系
	"f.game_mode != 1 && !ca.avg_ck('zb02') && ca.avg_ck('zb01') && f.used.調教値.Freya >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb02",1,0,1,0,"豊穣神の胸奉仕",1,//豊穣神の胸奉仕▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb03') && ca.avg_ck('zb02') && f.used.調教値.Freya >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb03",1,0,1,0,"搾乳調教",1,//搾乳調教▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb04') && ca.avg_ck('zb03') && f.used.調教値.Freya >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb04",1,0,1,0,"楽への耽溺",1,//楽への耽溺▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb05') && ca.avg_ck('zb04') && f.used.調教値.Freya >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb05",1,0,1,0,"堕落の豊穣神",1,//堕落の豊穣神▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw04') && ca.avg_ck('xc04') &&!ca.avg_ck('xb04')              && f.used.stat.story >= 2 && f.used.stat.story <= 8 && f.friend['Freya'] && f.friend['Thor']== 1 "	,"*zw04",1,0,1,0,"酒乱女神",1,//酒乱女神▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb06') && ca.avg_ck('zb05') && f.used.調教値.Freya >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb06",1,0,1,0,"放蕩の淫乱奉仕",1,//放蕩の淫乱奉仕▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb07') && ca.avg_ck('zb06') && f.used.調教値.Freya >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb07",1,0,1,0,"少年乱交",1,//少年乱交▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zb08') && ca.avg_ck('zb07') && f.used.調教値.Freya >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 "	,"*zb08",1,0,1,0,"完全牝牛化",1,//完全牝牛化▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw06') && ca.avg_ck('xb04') && ca.avg_ck('xc04')             && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] && f.friend['Thor']== 1 "	,"*zw06",1,0,1,0,"女神の囲い",1,//女神の囲い▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xb07') &&!ca.avg_ck('xb04') && f.used.親交値.Freya >= 99*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya']== 1 && f.フレイヤ好感度 >= 3 "	,"*xb07",1,0,1,0,"真なる月",1,//真なる月
	"f.friend['Freya']== 0 || ca.avg_ck('xb07') "	,"",1,0,1,0,"",1,//フレイヤイベントの解除条件（善ラストイベントをみるともうコールは発動不可）

	//トール
	"f.game_mode != 1 && !ca.avg_ck('yc01') &&                      f.used.親交値.Thor >= 10*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 0 "	,"*yc01",1,0,1,0,"ド根性女神",2,//ド根性女神
	"f.game_mode != 1 && !ca.avg_ck('yc02') && ca.avg_ck('yc01') && f.used.親交値.Thor >= 20*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 0 "	,"*yc02",1,0,1,0,"とある淫魔の禁書目録",2,//とある淫魔の禁書目録
	"f.game_mode != 1 && !ca.avg_ck('yc03') && ca.avg_ck('yc02') && f.used.親交値.Thor >= 30*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 0 "	,"*yc03",1,0,1,0,"女として戦士として",2,//女として戦士として
	"f.game_mode != 1 && !ca.avg_ck('yc04') && ca.avg_ck('yc03') && f.used.親交値.Thor >= 40*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 0 "	,"*yc04",1,0,1,0,"トール式マッサージ",2,//トール式マッサージ
	"f.game_mode != 1 && !ca.avg_ck('yc05') &&                      f.used.親交値.Thor >= 50*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 1 "	,"*yc05",1,0,1,0,"悪酔いトール",2,//悪酔いトール
	"f.game_mode != 1 && !ca.avg_ck('yc06') && ca.avg_ck('yc05') && f.used.親交値.Thor >= 60*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 1 "	,"*yc06",1,0,1,0,"自主トレは計画的に",2,//自主トレは計画的に
	"f.game_mode != 1 && !ca.avg_ck('yc07') && ca.avg_ck('yc06') && f.used.親交値.Thor >= 70*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 1 "	,"*yc07",1,0,1,0,"トルドハイム鉱山",2,//トルドハイム鉱山
	"f.game_mode != 1 && !ca.avg_ck('yc08') && ca.avg_ck('yc07') && f.used.親交値.Thor >= 80*f.K      && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Thor']== 1 && f.metamor03 == 1 "	,"*yc08",1,0,1,0,"無差別兵器",2,//無差別兵器
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",2,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('yc09') && ca.avg_ck('s852c')&& ca.avg_ck('zc09')                 && f.used.stat.story == 8                           && f.friend['Thor']== 1 && f.route == 'chaos'     "	,"*yc09",1,0,1,0,"変わりゆく従属神",2,//変わりゆく従属神
	"f.game_mode != 1 && !ca.avg_ck('yc10') && ca.avg_ck('zc10')                                      && f.used.stat.story == 8                           && f.friend['Thor']== 1 && f.route == 'chaos'     "	,"*yc10",1,0,1,0,"鬼神",2,//鬼神
	//トールＨ系
	"f.game_mode != 1 && !ca.avg_ck('zc02') && ca.avg_ck('zc01') && f.used.調教値.Thor >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc02",1,0,1,0,"絶倫セックス",2,//絶倫セックス▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc03') && ca.avg_ck('zc02') && f.used.調教値.Thor >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc03",1,0,1,0,"擬態服の罠",2,//擬態服の罠▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc04') && ca.avg_ck('zc03') && f.used.調教値.Thor >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc04",1,0,1,0,"肉欲に染まる信仰",2,//肉欲に染まる信仰▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc06') && ca.avg_ck('zc04') && f.used.調教値.Thor >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc06",1,0,1,0,"女神の褒賞",2,//女神の褒賞▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc05') && ca.avg_ck('zc06') && f.used.調教値.Thor >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc05",1,0,1,0,"陥落のレズプレイ",2,//陥落のレズプレイ▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw05') && ca.avg_ck('xb04') &&!ca.avg_ck('zc05')            && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] && f.friend['Thor']== 1 "	,"*zw05",1,0,1,0,"魅了されし少年達",2,//魅了されし少年達▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc07') && ca.avg_ck('zc06') && f.used.調教値.Thor >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc07",1,0,1,0,"情動の交尾",2,//情動の交尾▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc08') && ca.avg_ck('zc07') && f.used.調教値.Thor >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc08",1,0,1,0,"褒賞は輪姦で",2,//褒賞は輪姦で▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zc09') && ca.avg_ck('zc08') && f.used.調教値.Thor >= 80*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 "	,"*zc09",1,0,1,0,"家畜の背中",2,//家畜の背中▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw06') && ca.avg_ck('xb04') && ca.avg_ck('xc04')            && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Freya'] && f.friend['Thor']== 1 "	,"*zw06",1,0,1,0,"女神の囲い",2,//女神の囲い▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xc07') &&!ca.avg_ck('xc04') && f.used.親交値.Thor >= 99*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Thor']== 1 && f.トール好感度 >= 3 "	,"*xc07",1,0,1,0,"正義の稲妻",2,//正義の稲妻
	"f.friend['Thor']== 0 || ca.avg_ck('xc07') "	,"",1,0,1,0,"",2,//トールイベントの解除条件（善ラストイベントをみるともうコールは発動不可）

	//リグレット
	"f.game_mode != 1 && !ca.avg_ck('yd01') &&                      f.used.親交値.Regret >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 0 "	,"*yd01",1,0,1,0,"本の虫",3,//本の虫
	"f.game_mode != 1 && !ca.avg_ck('yd02') && ca.avg_ck('yd01') && f.used.親交値.Regret >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 0 "	,"*yd02",1,0,1,0,"不浄添い役",3,//不浄添い役
	"f.game_mode != 1 && !ca.avg_ck('yd03') && ca.avg_ck('yd02') && f.used.親交値.Regret >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 0 "	,"*yd03",1,0,1,0,"ヤーラルホーンのエール",3,//ヤーラルホーンのエール
	"f.game_mode != 1 && !ca.avg_ck('yd04') && ca.avg_ck('yd03') && f.used.親交値.Regret >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 0 "	,"*yd04",1,0,1,0,"グラーズ民芸品",3,//グラーズ民芸品
	"f.game_mode != 1 && !ca.avg_ck('yd05') &&                      f.used.親交値.Regret >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 1 "	,"*yd05",1,0,1,0,"祝福と呪いの盾",3,//祝福と呪いの盾
	"f.game_mode != 1 && !ca.avg_ck('yd06') && ca.avg_ck('yd05') && f.used.親交値.Regret >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 1 "	,"*yd06",1,0,1,0,"シーツの行方",3,//シーツの行方
	"f.game_mode != 1 && !ca.avg_ck('yd07') && ca.avg_ck('yd06') && f.used.親交値.Regret >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 1 "	,"*yd07",1,0,1,0,"ウソ泣き",3,//ウソ泣き
	"f.game_mode != 1 && !ca.avg_ck('yd08') && ca.avg_ck('yd07') && f.used.親交値.Regret >= 80*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Regret']== 1 && f.metamor04 == 1 "	,"*yd08",1,0,1,0,"飛翔船運用論",3,//飛翔船運用論
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",3,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('yd09') && ca.avg_ck('s852d')&& ca.avg_ck('zd08')                                        && f.used.stat.story == 8 && f.friend['Regret']== 1 && f.route == 'chaos'     "	,"*yd09",1,0,1,0,"共に在るカタチ",3,//共に在るカタチ
	"f.game_mode != 1 && !ca.avg_ck('yd10') && ca.avg_ck('zd09')                                                             && f.used.stat.story == 8 && f.friend['Regret']== 1 && f.route == 'chaos'     "	,"*yd10",1,0,1,0,"人形兵団",3,//人形兵団
	//リグレットＨ系
	"f.game_mode != 1 && !ca.avg_ck('zd02') && ca.avg_ck('zd01') && f.used.調教値.Regret >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd02",1,0,1,0,"躾と粗相",3,//躾と粗相▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd03') && ca.avg_ck('zd02') && f.used.調教値.Regret >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd03",1,0,1,0,"恥辱の会議",3,//恥辱の会議▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd04') && ca.avg_ck('zd03') && f.used.調教値.Regret >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd04",1,0,1,0,"肛門出産の快楽",3,//肛門出産の快楽▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd05') && ca.avg_ck('zd04') && f.used.調教値.Regret >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd05",1,0,1,0,"望む喪失",3,//望む喪失▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw01') && ca.avg_ck('xa04') && !ca.avg_ck('zd05')             && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Tilca'] && f.friend['Regret']== 1 "	,"*zw01",1,0,1,0,"姉の囁きと惑う妹",3,//姉の囁きと惑うリグレット▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd06') && ca.avg_ck('zd05') && f.used.調教値.Regret >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd06",1,0,1,0,"欲情のリグレット",3,//欲情のリグレット▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd07') && ca.avg_ck('zd06') && f.used.調教値.Regret >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd07",1,0,1,0,"飽食の奉仕者",3,//飽食の奉仕者▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zd08') && ca.avg_ck('zd07') && f.used.調教値.Regret >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 "	,"*zd08",1,0,1,0,"折檻木馬責め",3,//折檻木馬責め▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zw03') && ca.avg_ck('xa04') && ca.avg_ck('xd04')              && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Tilca'] && f.friend['Regret']== 1 "	,"*zw03",1,0,1,0,"痴女姉妹の散歩",3,//痴女姉妹の散歩▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xd07') &&!ca.avg_ck('xd04') && f.used.親交値.Regret >= 99*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Regret']== 1 && f.リグレット好感度 >= 3 "	,"*xd07",1,0,1,0,"雪国の秘湯開発",3,//雪国の秘湯開発
	"f.friend['Regret']== 0 || ca.avg_ck('xd07') "	,"",1,0,1,0,"",3,//リグレットイベントの解除条件（善ラストイベントをみるともうコールは発動不可）

	//オーディン
	"f.game_mode != 1 && !ca.avg_ck('ye01') &&                      f.used.親交値.Odin >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 0 "	,"*ye01",1,0,1,0,"興味津々",4,//興味津々
	"f.game_mode != 1 && !ca.avg_ck('ye02') && ca.avg_ck('ye01') && f.used.親交値.Odin >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 0 "	,"*ye02",1,0,1,0,"神の雷",4,//神の雷
	"f.game_mode != 1 && !ca.avg_ck('ye03') && ca.avg_ck('ye02') && f.used.親交値.Odin >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 0 "	,"*ye03",1,0,1,0,"思い悩む神",4,//思い悩む神
	"f.game_mode != 1 && !ca.avg_ck('ye04') && ca.avg_ck('ye03') && f.used.親交値.Odin >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 0 "	,"*ye04",1,0,1,0,"素直になるという事",4,//素直になるという事
	"f.game_mode != 1 && !ca.avg_ck('ye05') &&                      f.used.親交値.Odin >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 1 "	,"*ye05",1,0,1,0,"神様のお料理万歳",4,//神様のお料理万歳
	"f.game_mode != 1 && !ca.avg_ck('ye06') && ca.avg_ck('ye05') && f.used.親交値.Odin >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 1 "	,"*ye06",1,0,1,0,"主神のお料理能才",4,//主神のお料理能才
	"f.game_mode != 1 && !ca.avg_ck('ye07') && ca.avg_ck('ye06') && f.used.親交値.Odin >= 70*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 1 "	,"*ye07",1,0,1,0,"神様の躾け方",4,//神様の躾け方
	"f.game_mode != 1 && !ca.avg_ck('ye08') && ca.avg_ck('ye07') && f.used.親交値.Odin >= 80*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Odin']== 1 && f.metamor05 == 1 "	,"*ye08",1,0,1,0,"眠り姫",4,//眠り姫
//▲オーディンの09はボツ	"f.game_mode != 1 && !ca.avg_ck('ye09') && ca.avg_ck('ze07') && f.used.stat.story == 8 && f.route == 'chaos'   && f.friend['Odin']== 1                    "	,"*ye09",1,0,1,0,"邪悪への道",4,//邪悪への道
//▲オーディンの10はボツ	"f.game_mode != 1 && !ca.avg_ck('ye10') && ca.avg_ck('ye09') && f.used.stat.story == 8 && f.route == 'chaos'   && f.friend['Odin']== 1                    "	,"*ye10",1,0,1,0,"奴隷主神",4,//奴隷主神
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",4,//上記の解除条件
	//オーディンＨ系
	"f.game_mode != 1 && !ca.avg_ck('ze02') && ca.avg_ck('ze01') && f.used.調教値.Odin >= 10*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze02",1,0,1,0,"オーディン初性交",4,//オーディン初性交▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('ze03') && ca.avg_ck('ze02') && f.used.調教値.Odin >= 20*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze03",1,0,1,0,"尻穴スライム注入",4,//尻穴スライム注入▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('ze04') && ca.avg_ck('ze03') && f.used.調教値.Odin >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze04",1,0,1,0,"アルラウネダンス",4,//アルラウネダンス▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('ze05') && ca.avg_ck('ze04') && f.used.調教値.Odin >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze05",1,0,1,0,"絶対者の敗北",4,//絶対者の敗北▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('ze06') && ca.avg_ck('ze05') && f.used.調教値.Odin >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze06",1,0,1,0,"淫花の誘い",4,//淫花の誘い▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('ze07') && ca.avg_ck('ze06') && f.used.調教値.Odin >= 60*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 "	,"*ze07",1,0,1,0,"小さき絶対淫魔",4,//小さき絶対淫魔▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xe07') &&!ca.avg_ck('xe04') && f.used.親交値.Odin >= 99*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 8 && f.friend['Odin']== 1 && f.オーディン好感度 >= 3 "	,"*xe07",1,0,0,0,"いつかくるその日まで",4,//いつかくるその日まで
	"f.friend['Odin']== 0 || ca.avg_ck('xe07') "	,"",1,0,1,0,"",4,//オーディンイベントの解除条件（善ラストイベントをみるともうコールは発動不可）

	//フェーナ
	"f.game_mode != 1 && !ca.avg_ck('yh01') &&                      f.used.親交値.Ferna >= 10*f.K && f.used.stat.story >= 1 && f.used.stat.story <= 2 && f.friend['Ferna']== 1"	,"*yh01",1,0,1,0,"捕虜の処遇",5,//捕虜の処遇
	"f.game_mode != 1 && !ca.avg_ck('yh02') && ca.avg_ck('yh01') && f.used.親交値.Ferna >= 20*f.K && f.used.stat.story >= 1 && f.used.stat.story <= 2 && f.friend['Ferna']== 1"	,"*yh02",1,0,1,0,"候補者達の下馬評",5,//候補者達の下馬評
	"f.used.stat.story >= 3 "	,"",1,0,1,0,"",5,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('yh03') &&                      f.used.親交値.Ferna >= 30*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 4 && f.friend['Ferna']== 1"	,"*yh03",1,0,1,0,"傘でありたい",5,//傘でありたい
	"f.game_mode != 1 && !ca.avg_ck('yh04') && ca.avg_ck('yh03') && f.used.親交値.Ferna >= 40*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 4 && f.friend['Ferna']== 1"	,"*yh04",1,0,1,0,"懐柔か暗殺か",5,//懐柔か暗殺か
	"f.game_mode != 1 && !ca.avg_ck('yh08') && ca.avg_ck('yh04') && f.used.親交値.Ferna >= 50*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 4 && f.friend['Ferna']== 1"	,"*yh08",1,0,1,0,"メニア視察",5,//メニア視察
	"f.used.stat.story >= 5 "	,"",1,0,1,0,"",5,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('yh05') &&                      f.used.親交値.Ferna >= 60*f.K && f.used.stat.story >= 5 && f.used.stat.story <= 6 && f.friend['Ferna']== 1"	,"*yh05",1,0,1,0,"ロキの不覚",5,//ロキの不覚
	"f.game_mode != 1 && !ca.avg_ck('yh06') && ca.avg_ck('yh05') && f.used.親交値.Ferna >= 70*f.K && f.used.stat.story >= 5 && f.used.stat.story <= 6 && f.friend['Ferna']== 1"	,"*yh06",1,0,1,0,"どっちの料理",5,//どっちの料理
	"f.game_mode != 1 && !ca.avg_ck('yh07') && ca.avg_ck('yh06') && f.used.親交値.Ferna >= 80*f.K && f.used.stat.story >= 5 && f.used.stat.story <= 6 && f.friend['Ferna']== 1"	,"*yh07",1,0,1,0,"移民と先住民",5,//移民と先住民
	"f.used.stat.story >= 7 "	,"",1,0,1,0,"",5,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('zh02') && ca.avg_ck('zh01') && f.used.親交値.Ferna >= 15*f.K && f.used.stat.story >= 1 && f.used.stat.story <= 7 && f.friend['Ferna']== 1 ","*zh02",1,0,1,0,"フェーナのお勤め",5,//フェーナのお勤め▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zh03') && ca.avg_ck('zh02') && f.used.親交値.Ferna >= 35*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Ferna']== 1 ","*zh03",1,0,1,0,"小さな暴君",5,//小さな暴君▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('zh04') && ca.avg_ck('zh03') && f.used.親交値.Ferna >= 55*f.K && f.used.stat.story >= 3 && f.used.stat.story <= 7 && f.friend['Ferna']== 1 ","*zh04",1,0,1,0,"同体スワッピング",5,//同体スワッピング▲Ｈシーン
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",5,//上記の解除条件
	"f.game_mode != 1 && !ca.avg_ck('zp01') &&                      f.used.親交値.Ferna >= 90*f.K && f.used.stat.story == 8 && f.route == 'chaos' && f.friend['Ferna']== 1 && f.friend['Menia']== 1 "	,"*zp01",1,0,1,0,"触手の魔窟",5,//触手の魔窟▲Ｈシーン
	"f.friend['Ferna']== 0"	,"",1,0,1,0,"",5,//フェーナイベントの解除条件

	//ヘル
	"f.game_mode != 1 && !ca.avg_ck('xk01') &&                      f.used.親交値.Hel >= 10*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Hel']== 1"	,"*xk01",1,0,1,0,"師弟姉弟",6, //師弟姉弟
	"f.game_mode != 1 && !ca.avg_ck('yk01') && ca.avg_ck('xk01') && f.used.親交値.Hel >= 20*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Hel']== 1"	,"*yk01",1,0,1,0,"息吹く助太刀",6,//息吹く助太刀
	"f.game_mode != 1 && !ca.avg_ck('yk02') && ca.avg_ck('yk01') && f.used.親交値.Hel >= 30*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Hel']== 1"	,"*yk02",1,0,1,0,"荒野に雨を",6,//荒野に雨を
	"f.game_mode != 1 && !ca.avg_ck('yk04') && ca.avg_ck('yk02') && f.used.親交値.Hel >= 40*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Hel']== 1"	,"*yk04",1,0,1,0,"スカウト",6,//スカウト
	"f.game_mode != 1 && !ca.avg_ck('xk02') && ca.avg_ck('yk04') && f.used.親交値.Hel >= 50*f.K && f.used.stat.story == 7 &&                           f.friend['Hel']== 1"	,"*xk02",1,0,1,0,"重ねる父子",6,//重ねる父子
	"f.game_mode != 1 && !ca.avg_ck('yk03') && ca.avg_ck('xk02') && f.used.親交値.Hel >= 60*f.K && f.used.stat.story == 7 &&                           f.friend['Hel']== 1 "	,"*yk03",1,0,1,0,"愛憎の半ば",6,//愛憎の半ば
	"f.game_mode != 1 && !ca.avg_ck('xk03') && ca.avg_ck('zk01') && f.used.親交値.Hel >= 70*f.K && f.used.stat.story == 7 &&                           f.friend['Hel']== 1"	,"*xk03",1,0,1,0,"小さな悪巧み",6,//小さな悪巧み
	"f.game_mode != 1 && !ca.avg_ck('xk04') && ca.avg_ck('xk03') && f.used.親交値.Hel >= 80*f.K && f.used.stat.story == 7 &&                           f.friend['Hel']== 1"	,"*xk04",1,0,1,0,"矛を従えし王",6,//矛を従えし王
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",6, //上記の解除条件
	"f.friend['Hel']== 0"		,"",1,0,1,0,"",6,//ヘルイベントの解除条件

	//フェンリル
	"f.game_mode != 1 && !ca.avg_ck('yl01')                      && f.used.親交値.Fenrir >= 10*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Fenrir']== 1"	,"*yl01",1,0,1,0,"淫魔の邪魔",7,//淫魔の邪魔
	"f.game_mode != 1 && !ca.avg_ck('xl01') && ca.avg_ck('yl01') && f.used.親交値.Fenrir >= 20*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Fenrir']== 1"	,"*xl01",1,0,1,0,"お茶会の誘い",7,//お茶会の誘い
	"f.game_mode != 1 && !ca.avg_ck('xl02') && ca.avg_ck('xl01') && f.used.親交値.Fenrir >= 30*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Fenrir']== 1"	,"*xl02",1,0,1,0,"交換条件",7,//交換条件
	"f.game_mode != 1 && !ca.avg_ck('xl03') && ca.avg_ck('xl02') && f.used.親交値.Fenrir >= 40*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Fenrir']== 1"	,"*xl03",1,0,1,0,"夜襲明け",7,//夜襲明け
	"f.game_mode != 1 && !ca.avg_ck('zl02') && ca.avg_ck('xl03') && f.used.親交値.Fenrir >= 50*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Fenrir']== 1 "	,"*zl02",1,0,1,0,"淫魔の約束",7,//淫魔の約束▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xl04') && ca.avg_ck('zl02') && f.used.親交値.Fenrir >= 60*f.K && f.used.stat.story == 7 &&                           f.friend['Fenrir']== 1"	,"*xl04",1,0,1,0,"フェンリル負傷",7,//フェンリル負傷
	"f.game_mode != 1 && !ca.avg_ck('yl02') && ca.avg_ck('xl04') && f.used.親交値.Fenrir >= 70*f.K && f.used.stat.story == 7 &&                           f.friend['Fenrir']== 1"	,"*yl02",1,0,1,0,"色町諜報部",7,//色町諜報部
	"f.game_mode != 1 && !ca.avg_ck('yl03') && ca.avg_ck('yl02') && f.used.親交値.Fenrir >= 80*f.K && f.used.stat.story == 7 &&                           f.friend['Fenrir']== 1"	,"*yl03",1,0,1,0,"氷漬けの彫像",7,//氷漬けの彫像
	"f.game_mode != 1 && !ca.avg_ck('yl04') && ca.avg_ck('yl03') && f.used.親交値.Fenrir >= 90*f.K && f.used.stat.story == 7 &&                           f.friend['Fenrir']== 1"	,"*yl04",1,0,1,0,"帰らない斥候",7,//帰らない斥候
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",7,//上記の解除条件
	"f.friend['Fenrir']== 0"	,"",1,0,1,0,"",7,//フェンリルイベントの解除条件

	//ヨルム
	"f.game_mode != 1 && !ca.avg_ck('ym01')                      && f.used.親交値.Jormu >= 10*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Jormu']== 1"	,"*ym01",1,0,1,0,"一番うまく使えるの",8,//一番うまく使えるの
	"f.game_mode != 1 && !ca.avg_ck('zm01') && ca.avg_ck('ym01') && f.used.親交値.Jormu >= 20*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Jormu']== 1 "	,"*zm01",1,0,1,0,"ヨルム擽り責め",8,//ヨルム擽り責め▲Ｈシーン
	"f.game_mode != 1 && !ca.avg_ck('xm01') && ca.avg_ck('zm01') && f.used.親交値.Jormu >= 30*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Jormu']== 1"	,"*xm01",1,0,1,0,"忘れものはなに",8,//忘れものはなに
	"f.game_mode != 1 && !ca.avg_ck('xm02') && ca.avg_ck('xm01') && f.used.親交値.Jormu >= 40*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Jormu']== 1"	,"*xm02",1,0,1,0,"ヨルムの過去",8,//ヨルムの過去
	"f.game_mode != 1 && !ca.avg_ck('ym02') && ca.avg_ck('xm02') && f.used.親交値.Jormu >= 50*f.K && f.used.stat.story >= 2 && f.used.stat.story <= 7 && f.friend['Jormu']== 1"	,"*ym02",1,0,1,0,"悲鳴を聞かせて",8,//悲鳴を聞かせて
	"f.game_mode != 1 && !ca.avg_ck('xm03') && ca.avg_ck('ym02') && f.used.親交値.Jormu >= 60*f.K && f.used.stat.story == 7 &&                           f.friend['Jormu']== 1"	,"*xm03",1,0,1,0,"狂いし魔術式",8,//狂いし魔術式
	"f.game_mode != 1 && !ca.avg_ck('xm04') && ca.avg_ck('xm03') && f.used.親交値.Jormu >= 70*f.K && f.used.stat.story == 7 &&                           f.friend['Jormu']== 1"	,"*xm04",1,0,1,0,"可愛さ余って……",8,//可愛さ余って……
	"f.game_mode != 1 && !ca.avg_ck('ym03') && ca.avg_ck('xm04') && f.used.親交値.Jormu >= 80*f.K && f.used.stat.story == 7 &&                           f.friend['Jormu']== 1"	,"*ym03",1,0,1,0,"意外な才能",8,//意外な才能
	"f.game_mode != 1 && !ca.avg_ck('ym04') && ca.avg_ck('ym03') && f.used.親交値.Jormu >= 90*f.K && f.used.stat.story == 7 &&                           f.friend['Jormu']== 1"	,"*ym04",1,0,1,0,"泥酔ヨルム",8,//泥酔ヨルム
	"f.used.stat.story >= 8 "	,"",1,0,1,0,"",8,//上記の解除条件
	"f.friend['Jormu']== 0"	,"",1,0,1,0,"",8	//ヨルムイベントの解除条件

	];

var _MEDALION_POS= [
						0,1,2,13,14,15,16,17,
						3,4,5,6,7,18,19,20,21,22,
						8,9,10,23,
						11,24,
						12,25,
						26,
						27,28,29
	];
	
var _MEDALION_BUYS= [
						1,1,1,1,1,1,
						1,1,1,1,1,1,
						1,1,1,1,1,1,
						1,1,1,1,0,0,
						0,0,0,0,0,0
	];
